version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: apartment-listing-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - apartment-network
    environment:
      - MONGO_INITDB_DATABASE=apartment-listing

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apartment-listing-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/apartment-listing
    depends_on:
      - mongodb
    networks:
      - apartment-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apartment-listing-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000/api
    depends_on:
      - backend
    networks:
      - apartment-network

networks:
  apartment-network:
    driver: bridge

volumes:
  mongodb_data: 